// Exercises
export const EXERCISES_LOADING = 'EXERCISES_LOADING';
export const ADD_EXERCISES = 'ADD_EXERCISES';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const EXERCISES_FAILED = 'EXERCISES_FAILED';